# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios'
target 'LeadMovies' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LeadMovies
#pod  'react-native-gesture-handler', '1.0.10'
#pod 'react-navigation' '3.0.5'

  target 'LeadMovies-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'LeadMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'LeadMovies-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LeadMovies-tvOS

# target 'LeadMovies-tvOSTests' do
#   inherit! :search_paths
    # Pods for testing
# end

#end


